### ISSUE TITLE
Collab editor bugs

### ISSUE THREAD

**Issue by benmurphyy** [CS3219-AY2324S1/ay2324s1-course-assessment-g28#77]
- when the ws session finally times out, no notification is sent to users. They are just stuck on loading screen. This could be related to the fact that the collab service errors out in certain scenarios (container just goes down). Example console log here:
![Screenshot 2023-11-07 at 11 36 05 PM](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g28/assets/47269122/b7ff60c1-9eaf-4926-9da8-c80bf037fc59)

- after someone officially leaves a session, they are still able to rejoin the session. This should not be possible. The session should be removed from thier active sessions in the database. For the user that remains in the session, he should still be able to access the session, until he submits his code or he does not rejoin the session for a specifica amount of time.

- whenever rejoining a session, the other user must refresh their page in order for me to properly rejoin and not see the loading screen

**Comment by winsonheng** [comment]
Fixed but I've set it such that a user can rejoin even after officially exiting as long as the partner is still active. If both users leave, the session will still be joinable for 1 hour
